# Generated by Django 2.2.5 on 2020-05-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0002_mbti_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='post'),
        ),
    ]
