# Generated by Django 2.2.5 on 2020-05-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0003_auto_20200504_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='content',
            field=models.TextField(max_length=4000, verbose_name='post'),
        ),
    ]
